// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalon_BusinessObject.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public string Status { get; set; }

    public DateTime? BookingDate { get; set; }

    public decimal? Amount { get; set; }

    public int? CreateBy { get; set; }

    public decimal? Discount { get; set; }

    public int UserId { get; set; }

    public virtual ICollection<BookingDetail> BookingDetails { get; set; } = new List<BookingDetail>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual User User { get; set; }
}