// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalon_BusinessObject.Models;

public partial class BookingDetail
{
    public int BookingDetailId { get; set; }

    public int BookingId { get; set; }

    public int ServiceId { get; set; }

    public int StylistId { get; set; }

    public DateTime ScheduledWorkingDay { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Service Service { get; set; }

    public virtual Stylist Stylist { get; set; }
}