// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalon_BusinessObject.Models;

public partial class BookingDetail
{
    public string BookingDetailId { get; set; }

    public string BookingId { get; set; }

    public string ServiceId { get; set; }

    public string StylistId { get; set; }

    public DateTime ScheduledWorkingDay { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Service Service { get; set; }

    public virtual Stylsit Stylist { get; set; }
}