// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalon_BusinessObject.Models;

public partial class Earning
{
    public int EarningId { get; set; }

    public int UserId { get; set; }

    public decimal? Commission { get; set; }

    public virtual User User { get; set; }
}