// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalon_BusinessObject.Models;

public partial class Earning
{
    public string EarningId { get; set; }

    public string StylistId { get; set; }

    public decimal Commission { get; set; }

    public decimal TotalSalary { get; set; }

    public virtual Stylsit Stylist { get; set; }
}