// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalon_BusinessObject.Models;

public partial class Feedback
{
    public int FeedbackId { get; set; }

    public string Interest { get; set; }

    public string Description { get; set; }

    public int? BookingdetailId { get; set; }

    public virtual BookingDetail Bookingdetail { get; set; }
}