// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalon_BusinessObject.Models;

public partial class Payment
{
    public int PaymentId { get; set; }

    public int BookingId { get; set; }

    public DateTime TransactionDate { get; set; }

    public string TransactionType { get; set; }

    public decimal Amount { get; set; }

    public string Status { get; set; }
}