// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalon_BusinessObject.Models;

public partial class Role
{
    public string RoleId { get; set; }

    public string RoleName { get; set; }

    public virtual ICollection<User> User { get; set; } = new List<User>();
}