// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalon_BusinessObject.Models;

public partial class Service
{
    public int ServiceId { get; set; }

    public string ServiceName { get; set; }

    public decimal? Price { get; set; }

    public string Description { get; set; }

    public string Image { get; set; }

    public virtual ICollection<BookingDetail> BookingDetail { get; set; } = new List<BookingDetail>();
}