// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalon_BusinessObject.Models;

public partial class ServiceSlot
{
    public int ServiceSlotId { get; set; }

    public int SlotId { get; set; }

    public int StylistId { get; set; }

    public int ServiceId { get; set; }

    public DateTime Date { get; set; }
}