// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HairSalon_BusinessObject.Models;

public partial class StylistProfile
{
    public int UserId { get; set; }

    public decimal? Salary { get; set; }

    public double? DailySalary { get; set; }

    public DateOnly? Date { get; set; }

    public virtual User User { get; set; }
}