// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace HairSalon_BusinessObject.Models;

public partial class HairSalonContext : DbContext
{
    public HairSalonContext()
    {
    }

    public HairSalonContext(DbContextOptions<HairSalonContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Booking> Booking { get; set; }

    public virtual DbSet<BookingDetail> BookingDetail { get; set; }

    public virtual DbSet<Earning> Earning { get; set; }

    public virtual DbSet<Payment> Payment { get; set; }

    public virtual DbSet<Role> Role { get; set; }

    public virtual DbSet<Service> Service { get; set; }

    public virtual DbSet<ServiceSlot> ServiceSlot { get; set; }

    public virtual DbSet<Slot> Slot { get; set; }

    public virtual DbSet<Stylist> Stylist { get; set; }

    public virtual DbSet<User> User { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=localhost;Initial Catalog=HairSalon;User ID=SA;Password=12345;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Booking>(entity =>
        {
            entity.Property(e => e.BookingId).HasColumnName("bookingId");
            entity.Property(e => e.BookingDate)
                .HasColumnType("datetime")
                .HasColumnName("bookingDate");
            entity.Property(e => e.CreateBy)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("createBy");
            entity.Property(e => e.Discount)
                .HasColumnType("decimal(3, 0)")
                .HasColumnName("discount");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.TotalPrice)
                .HasColumnType("money")
                .HasColumnName("totalPrice");
        });

        modelBuilder.Entity<BookingDetail>(entity =>
        {
            entity.Property(e => e.BookingDetailId).HasColumnName("bookingDetailId");
            entity.Property(e => e.BookingId).HasColumnName("bookingId");
            entity.Property(e => e.ScheduledWorkingDay)
                .HasColumnType("datetime")
                .HasColumnName("scheduledWorkingDay");
            entity.Property(e => e.ServiceId).HasColumnName("serviceId");
            entity.Property(e => e.StylistId).HasColumnName("stylistId");

            entity.HasOne(d => d.Booking).WithMany(p => p.BookingDetail)
                .HasForeignKey(d => d.BookingId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingDetail_Booking");

            entity.HasOne(d => d.Service).WithMany(p => p.BookingDetail)
                .HasForeignKey(d => d.ServiceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingDetail_Service");

            entity.HasOne(d => d.Stylist).WithMany(p => p.BookingDetail)
                .HasForeignKey(d => d.StylistId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookingDetail_Stylist");
        });

        modelBuilder.Entity<Earning>(entity =>
        {
            entity.Property(e => e.EarningId).HasColumnName("earningId");
            entity.Property(e => e.Commission)
                .HasColumnType("money")
                .HasColumnName("commission");
            entity.Property(e => e.StylistId).HasColumnName("stylistId");
            entity.Property(e => e.TotalSalary)
                .HasColumnType("money")
                .HasColumnName("totalSalary");

            entity.HasOne(d => d.Stylist).WithMany(p => p.Earning)
                .HasForeignKey(d => d.StylistId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Earning_Stylsit");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasNoKey();

            entity.Property(e => e.Amount)
                .HasColumnType("money")
                .HasColumnName("amount");
            entity.Property(e => e.BookingId).HasColumnName("bookingId");
            entity.Property(e => e.PaymentId).HasColumnName("paymentId");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.TransactionDate)
                .HasColumnType("datetime")
                .HasColumnName("transactionDate");
            entity.Property(e => e.TransactionType)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("transactionType");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.Property(e => e.RoleId).HasColumnName("roleId");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("roleName");
        });

        modelBuilder.Entity<Service>(entity =>
        {
            entity.Property(e => e.ServiceId).HasColumnName("serviceId");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("description");
            entity.Property(e => e.Image)
                .IsRequired()
                .HasColumnType("image")
                .HasColumnName("image");
            entity.Property(e => e.Price)
                .HasColumnType("money")
                .HasColumnName("price");
            entity.Property(e => e.ServiceName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("serviceName");
        });

        modelBuilder.Entity<ServiceSlot>(entity =>
        {
            entity.HasNoKey();

            entity.Property(e => e.Date)
                .HasColumnType("datetime")
                .HasColumnName("date");
            entity.Property(e => e.ServiceId).HasColumnName("serviceId");
            entity.Property(e => e.ServiceSlotId).HasColumnName("serviceSlotId");
            entity.Property(e => e.SlotId).HasColumnName("slotId");
            entity.Property(e => e.StylistId).HasColumnName("stylistId");
        });

        modelBuilder.Entity<Slot>(entity =>
        {
            entity.HasNoKey();

            entity.Property(e => e.EndStart).HasColumnName("endStart");
            entity.Property(e => e.SlotId).HasColumnName("slotId");
            entity.Property(e => e.StartTime).HasColumnName("startTime");
        });

        modelBuilder.Entity<Stylist>(entity =>
        {
            entity.HasKey(e => e.StylistId).HasName("PK_Stylsit");

            entity.Property(e => e.StylistId).HasColumnName("stylistId");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("fullName");
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("phoneNumber");
            entity.Property(e => e.Salary)
                .HasColumnType("money")
                .HasColumnName("salary");
            entity.Property(e => e.Specialty)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("specialty");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.Property(e => e.UserId).HasColumnName("userId");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("email");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("password");
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("phoneNumber");
            entity.Property(e => e.RoleId).HasColumnName("roleId");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("userName");

            entity.HasOne(d => d.Role).WithMany(p => p.User)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_User_Role");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}